#!/usr/bin/env python3
"""
new_company.py — scaffold a company folder and print the asset shopping list.

    python3 new_company.py EICHERMOT --name "Eicher Motors Ltd"

Creates:
    companies/EICHERMOT/
        inputs/          <- you drop source documents here
        assets/          <- you drop images here (logo, products, directors, plants)
        charts/          <- generated by charts.py
        data/            <- generated by parse_screener.py + model.py
        assumptions.json <- edit before running model.py
        ASSETS.md        <- the checklist of images/documents still needed
"""
from __future__ import annotations

import argparse
import json
import os

DIRS = ["inputs", "assets/products", "assets/people", "assets/plants", "assets/exhibits",
        "charts", "data"]

ASSUMPTIONS = {
    "_comment": "Every rate may be given as a decimal (0.068) or a percent (6.8). "
                "Per-year lists override the single value. Delete a key to fall back "
                "to the historical average (model.py will tell you when it did).",
    "rf": 6.8,
    "erp": 5.5,
    "beta": 1.0,
    "cost_of_debt": 8.0,
    "tax_rate": 25.17,
    "target_debt_weight": 0.0,
    "forecast_years": 5,
    "revenue_growth": [14.0, 12.0, 11.0, 10.0, 9.0],
    "ebit_margin": [20.0, 20.5, 20.5, 21.0, 21.0],
    "capex_pct_sales": [6.0, 5.5, 5.0, 4.5, 4.5],
    "dep_pct_sales": [4.0, 4.0, 4.0, 4.0, 4.0],
    "nwc_pct_sales": [2.0, 2.0, 2.0, 2.0, 2.0],
    "terminal_growth": 5.0,
    "net_debt": None,
    "shares_out": None,
    "current_price": None,
    "peers": [
        {"name": "SUBJECT CO", "price": None, "mcap": None, "ev": None,
         "sales": None, "ebitda": None, "pat": None, "bv": None, "roe": None},
        {"name": "Peer 1", "price": None, "mcap": None, "ev": None,
         "sales": None, "ebitda": None, "pat": None, "bv": None, "roe": None}
    ],
}

CHECKLIST = """# Asset checklist — {ticker}

Tick each item off. `render.py` blocks the PDF while any referenced file is missing.
Filenames are conventions the report template expects — keep them exactly.

## Required documents -> `inputs/`
- [ ] `screener.xlsx`         Screener.in -> company page -> "Export to Excel"
- [ ] `annual_report.pdf`     latest FY annual report (for segments, RPT, auditor, contingent liabilities)
- [ ] `investor_presentation.pdf`  latest quarterly deck
- [ ] `concall.pdf` / `.txt`  latest earnings-call transcript
- [ ] `shareholding.pdf`      latest exchange shareholding filing (for the pledging line)

## Required images -> `assets/`
- [ ] `assets/logo.png`                   company logo, transparent background
- [ ] `assets/products/*.png`             6-12 product / brand shots, one file per product
- [ ] `assets/people/<surname>.jpg`       headshot per director and KMP you profile
- [ ] `assets/plants/footprint.png`       plant / global footprint map
- [ ] `assets/exhibits/*.png`             screenshots you crop yourself: group structure chart,
                                          segment slide, capacity table, auditor's report extract

Naming rule: lowercase, no spaces, use `-` not `_` inside a name.
Anything you cannot source: delete the section rather than shipping an empty frame.

## Assumptions
- [ ] `assumptions.json` filled in — especially `current_price`, `shares_out`, `net_debt`, `beta`, and the peer set.
      Leave a key out and the model uses the historical average, then tells you it did.
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("ticker")
    ap.add_argument("--name", default="")
    ap.add_argument("--root", default="companies")
    args = ap.parse_args()

    base = os.path.join(args.root, args.ticker.upper())
    for d in DIRS:
        os.makedirs(os.path.join(base, d), exist_ok=True)

    a = dict(ASSUMPTIONS)
    if args.name:
        a["peers"][0]["name"] = args.name
    ap_path = os.path.join(base, "assumptions.json")
    if not os.path.exists(ap_path):
        json.dump(a, open(ap_path, "w"), indent=2)

    cl = os.path.join(base, "ASSETS.md")
    if not os.path.exists(cl):
        open(cl, "w").write(CHECKLIST.format(ticker=args.ticker.upper()))

    print(f"scaffolded {base}\n")
    print(open(cl).read())


if __name__ == "__main__":
    main()
